### ISSUE TITLE
Add captcha to registration page

### ISSUE THREAD

**Issue by JohnClarke** [IBM/CyberSkill#13]

**Comment by jasoneflood** [comment]
I think it would be good if we also trapped more information during registration. Such as First/Last name, also maybe a faction name. So they could auto register themselves into their own factions rather than being assigned to a faction by us. 
Faction could be a free text field so they can create factions on signup

**Comment by JCFL-Dev** [comment]
Added request fields above. I've also hooked it up to Google Recaptcha I am not a robot. Contributors will have to create their own keys for captcha to work.
